# Generated by Django 5.2.2 on 2025-06-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('max_elevation', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured_image', models.ImageField(upload_to='treks/')),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_badge_text', models.CharField(blank=True, max_length=50)),
                ('highlights', models.TextField(help_text='Separate highlights with new lines')),
            ],
        ),
    ]
