# Generated by Django 5.2.2 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter each highlight on a new line'),
        ),
    ]
